# Generated by Django 3.2.5 on 2022-01-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=20)),
                ('email', models.EmailField(default='none', max_length=30)),
                ('subject', models.CharField(default='none', max_length=60)),
                ('message', models.CharField(default='none', max_length=200)),
                ('phone', models.IntegerField(default='none', max_length=20)),
            ],
        ),
    ]
