# Generated by Django 3.2.5 on 2022-01-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='subject',
        ),
    ]
