# Generated by Django 3.2.5 on 2022-01-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_alter_contactform_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(default='none', max_length=13),
        ),
    ]
