# Generated by Django 3.2.5 on 2022-01-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_auto_20220123_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='booktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=20)),
                ('email', models.EmailField(default='none', max_length=30)),
                ('phone', models.CharField(default='none', max_length=13)),
                ('date', models.DateField(default='none')),
                ('time', models.TimeField(default='none')),
                ('people', models.IntegerField(default='none')),
                ('message', models.TextField(default='none', max_length=200)),
            ],
        ),
    ]
