# Generated by Django 3.2.5 on 2022-01-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_booktable'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=19)),
                ('desc', models.TextField(max_length=50)),
                ('img', models.ImageField(default='none', upload_to='')),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
