# Generated by Django 3.2.5 on 2022-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_alter_menu_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='specials',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=19)),
                ('short_desc', models.TextField(max_length=50)),
                ('big_desc', models.TextField(max_length=50)),
                ('img', models.ImageField(default='none', upload_to='special_pics')),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(default='none', upload_to='menu_pics'),
        ),
    ]
