# Generated by Django 3.2.5 on 2022-01-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_auto_20220125_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specials',
            name='big_desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='specials',
            name='short_desc',
            field=models.TextField(max_length=70),
        ),
    ]
